AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: api
      CodeUri: bin/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          DB_HOST: host.docker.internal
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: brab
          DB_SSLMODE: disable
          DB_DEBUG: true
          AUTO_MIGRATE: true
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
