name = "bra-b-backend"
main = "worker.js"
compatibility_date = "2023-06-28"

[build]
command = "./build.sh"

# 静的アセットの設定
[site]
bucket = "./wasm"
# 開発環境用の設定
include = ["*.wasm"]
exclude = []

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true
